version: '2'
services:
  prod:
    build:
  node:
    build:
      context: .
    volumes:
      -  .:/opt
    links:
      - rabbitmq
    ports:
      - 8080:3000
      - 3001:3001
      - 6379:6379

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672