version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379


  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672

  prod:
    build: './mock/mock_prod/'
    environment:
      - rabbitHost=rabbitmq
      - rabbitPort=5672
