version: '3'

services:

  rabbitmqmock:
    image: 'rabbitmq:3-management'
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672

  prod:
    build: './mock_prod/'
    environment:
      - config_rabbitHost=rabbitmqmock
      - config_batchNumber=100

