version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379


  rabbitmq:
    container_name: rabbitMQ
    image: 'rabbitmq:3-management'
    ports:
      - 5679:5672
      - 15679:15672
      - 25679:25672


  consumer:
    container_name: consumer
    build: './consumer/'
    environment:
      - rabbitHost=10.0.75.1
      - rabbitPort=5672



